export const BROWSER_BLOCKED_GLOBALS = {
    setInterval: undefined,
    clearInterval: undefined,
    eval: undefined,
    window: undefined,
    self: undefined,
    globalThis: undefined,
    frames: undefined,
    parent: undefined,
    top: undefined,
    document: undefined,
    localStorage: undefined,
    sessionStorage: undefined,
    Function: undefined,
    XMLHttpRequest: undefined,
    WebSocket: undefined,
    EventSource: undefined,
    location: undefined,
    indexedDB: undefined,
};
export const SERVER_BLOCKED_GLOBALS = {
    setInterval: undefined,
    clearInterval: undefined,
    eval: undefined,
    globalThis: undefined,
    global: undefined,
    window: undefined,
    self: undefined,
    document: undefined,
    localStorage: undefined,
    sessionStorage: undefined,
    require: undefined,
    module: undefined,
    exports: undefined,
    __dirname: undefined,
    __filename: undefined,
    process: undefined,
    Function: undefined,
};
//# sourceMappingURL=blocked-globals.js.map